@startuml
class NyIngredientsFactory {
    CreateCheese() : ICheese
    CreateClam() : IClam
    CreateDough() : IDough
    CreateSauce() : ISauce
    CreateVeggies() : IEnumerable<IVeggies>
}
IIngredientsFactory <|-- NyIngredientsFactory
@enduml
