@startuml
interface IUnitVisitor {
    VisitApartment(apartment:Apartment) : void
    VisitStudio(studio:Studio) : void
    VisitBedroom(bedroom:Bedroom) : void
    VisitLivingRoom(livingRoom:LivingRoom) : void
}
@enduml
