@startuml
class LivingRoomVisitor {
    + VisitApartment(apartment:Apartment) : void
    + VisitStudio(studio:Studio) : void
    + VisitBedroom(bedroom:Bedroom) : void
    + VisitLivingRoom(livingRoom:LivingRoom) : void
}
IUnitVisitor <|-- LivingRoomVisitor
@enduml
