@startuml
class BreakfastMenuIterator {
    + BreakfastMenuIterator(items:ArrayList)
    GetEnumerator() : IEnumerator
    + GetEnumerator() : IEnumerator
}
IEnumerable <|-- BreakfastMenuIterator
@enduml
